export default {
  ADDRESSES_SET: { type: "ADDRESSES_SET" },
  ADDRESSES_EDIT_ONE: { type: "ADDRESSES_EDIT_ONE" },
  ADDRESSES_LOGOUT_INITIAL: { type: "ADDRESSES_LOGOUT_INITIAL" },
  ADDRESSES_DELETE_ONE: { type: "ADDRESSES_DELETE_ONE" },
  ADDRESSES_ADD_ONE: { type: "ADDRESSES_ADD_ONE" },
};
