export default {
  WISHLIST_SET: { type: "WISHLIST_SET" },
  WISHLIST_ADD_PRODUCT: { type: "WISHLIST_ADD_PRODUCT" },
  WISHLIST_DELETE_PRODUCT: { type: "WISHLIST_DELETE_PRODUCT" },
  WISHLIST_LOGOUT_INITIAL: { type: "WISHLIST_LOGOUT_INITIAL" },
};
